site_name: Calculator Docs

theme:
  name: "material"

plugins:
  - mkdocstrings

# use_directory_urls: false

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Explanation: explanation.md
  - Reference: reference.md